# This configuration file is for **development** setup. For production, refer to
# docker-compose.production.yml.
version: '3'
services:
  server:
    build: .
    command: dev_server
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"
      - "5678:5678"
    volumes:
      - ".:/app"
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_ALLOW_SCRIPTS_IN_USER_INPUT: "true"
      REDASH_ALLOW_PARAMETERS_IN_EMBEDS: "true"
      REDASH_THROTTLE_LOGIN_PATTERN: "500/minute"
      REDASH_ADDITIONAL_QUERY_RUNNERS: "redash.query_runner.python"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
  worker:
    build: .
    command: scheduler
    volumes:
      - ".:/app"
    depends_on:
      - server
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_ALLOW_SCRIPTS_IN_USER_INPUT: "true"
      REDASH_ALLOW_PARAMETERS_IN_EMBEDS: "true"
      REDASH_THROTTLE_LOGIN_PATTERN: "500/minute"
      REDASH_ADDITIONAL_QUERY_RUNNERS: "redash.query_runner.python"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      QUEUES: "queries,scheduled_queries,celery"
      WORKERS_COUNT: 2
  redis:
    image: redis:3-alpine
    restart: unless-stopped
  postgres:
    image: postgres:9.5-alpine
    # The following turns the DB into less durable, but gains significant performance improvements for the tests run (x3
    # improvement on my personal machine). We should consider moving this into a dedicated Docker Compose configuration for
    # tests.
    ports:
      - "15432:5432"
    command: "postgres -c fsync=off -c full_page_writes=off -c synchronous_commit=OFF"
    restart: unless-stopped
